import Head from "next/head";
import { Header } from "@/components/Header";
import Content from "@/components/Content";

function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
}

export default Home;
